# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - M-and-AI

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://myregisterya.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_8f8a0664d53841bb97539e6ca771bc10 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_c359806a5b484ca986931902f175e216 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: myregisterya.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_8f8a0664d53841bb97539e6ca771bc10 }}/myapp:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'M-and-AI'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_7a671e3c53b9494892963cd9205bb84c }}
        images: 'myregisterya.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_8f8a0664d53841bb97539e6ca771bc10 }}/myapp:${{ github.sha }}'